import { chromium } from '@playwright/test';
const BASE='https://chatwithpdfai.com';
const OUT='/sessions/sharp-wizardly-bell/mnt/CHATWITHPDFAI.COM/.cowork-private/_shots';
const b=await chromium.launch();
let ctx=await b.newContext({viewport:{width:1440,height:900},deviceScaleFactor:1});
let page=await ctx.newPage();
await page.goto(BASE+'/',{waitUntil:'networkidle'}); await page.waitForTimeout(1500);
await page.screenshot({path:OUT+'/home_desktop_fold.png'});
await page.screenshot({path:OUT+'/home_desktop_full.png',fullPage:true});
await ctx.close();
ctx=await b.newContext({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true});
page=await ctx.newPage();
await page.goto(BASE+'/',{waitUntil:'networkidle'}); await page.waitForTimeout(1500);
await page.screenshot({path:OUT+'/home_mobile_fold.png'});
await page.screenshot({path:OUT+'/home_mobile_full.png',fullPage:true});
await b.close();
console.log('shots done');
