// Exam blueprint registry for the question-paper generator.
// Pure data, no React, no I/O. The picker UI imports CATEGORIES from here.
//
//   presets[].sections  -> the focused, editable default (one fast AI call, <=40 Q)
//   presets[].real      -> OPTIONAL human string: the real exam's full spec (shown as a hint)
//   presets[].full      -> OPTIONAL real-size sections [{title,type,count,marks}] used by the
//                          "Full real-size exam" toggle, which generates in batches (<=30 Q/call)
//                          and stitches them into one paper. Omit for blueprints whose focused
//                          default is already real-size (e.g. CBSE board papers).
//
// `type` must be one of: mcq, multi, tf, fill, match, assertion, numeric, short, long, code.
export const CATEGORIES = [
  { k: 'exams', label: 'Govt / competitive exams', presets: [
    { label: 'TNPSC Group 4', examStyle: 'TNPSC Group 4', real: '200 Q / 300 marks / 1.5 each / no negative (real paper also has 100 Tamil Q)', topic: 'TNPSC Group 4 — Indian polity, history, geography, general science, current affairs and aptitude', sections: [{ title: 'General studies', type: 'mcq', count: 30, marks: 1.5 }, { title: 'Aptitude & mental ability', type: 'mcq', count: 10, marks: 1.5 }], full: [{ title: 'General studies', type: 'mcq', count: 75, marks: 1.5 }, { title: 'Aptitude & mental ability', type: 'mcq', count: 25, marks: 1.5 }] },
    { label: 'UPSC Prelims — GS Paper I', examStyle: 'UPSC Prelims GS Paper I', real: '100 Q / 200 marks / +2, -0.66 / 2 hr', topic: 'UPSC Civil Services Prelims — General Studies Paper I', sections: [{ title: 'General studies', type: 'mcq', count: 25, marks: 2 }], full: [{ title: 'General studies', type: 'mcq', count: 100, marks: 2 }] },
    { label: 'SSC CGL Tier-1', examStyle: 'SSC CGL Tier I', real: '100 Q / 200 marks / +2, -0.5 / 60 min (4 x 25)', topic: 'SSC CGL Tier 1 — reasoning, general awareness, quantitative aptitude, English', sections: [{ title: 'General intelligence & reasoning', type: 'mcq', count: 12, marks: 2 }, { title: 'General awareness', type: 'mcq', count: 12, marks: 2 }, { title: 'Quantitative aptitude', type: 'mcq', count: 12, marks: 2 }, { title: 'English comprehension', type: 'mcq', count: 12, marks: 2 }], full: [{ title: 'General intelligence & reasoning', type: 'mcq', count: 25, marks: 2 }, { title: 'General awareness', type: 'mcq', count: 25, marks: 2 }, { title: 'Quantitative aptitude', type: 'mcq', count: 25, marks: 2 }, { title: 'English comprehension', type: 'mcq', count: 25, marks: 2 }] },
  ] },
  { k: 'banking', label: 'Banking & insurance', presets: [
    { label: 'IBPS PO — Prelims', examStyle: 'IBPS PO Prelims', real: '100 Q / 100 marks / +1, -0.25 / 60 min', topic: 'IBPS PO Prelims — English language, quantitative aptitude, reasoning ability', sections: [{ title: 'English language', type: 'mcq', count: 15, marks: 1 }, { title: 'Quantitative aptitude', type: 'mcq', count: 15, marks: 1 }, { title: 'Reasoning ability', type: 'mcq', count: 15, marks: 1 }], full: [{ title: 'English language', type: 'mcq', count: 30, marks: 1 }, { title: 'Quantitative aptitude', type: 'mcq', count: 35, marks: 1 }, { title: 'Reasoning ability', type: 'mcq', count: 35, marks: 1 }] },
    { label: 'SBI PO — Prelims', examStyle: 'SBI PO Prelims', real: '100 Q / 100 marks / +1, -0.25 / 60 min', topic: 'SBI PO Prelims — English language, reasoning ability, quantitative aptitude', sections: [{ title: 'English language', type: 'mcq', count: 16, marks: 1 }, { title: 'Reasoning ability', type: 'mcq', count: 12, marks: 1 }, { title: 'Quantitative aptitude', type: 'mcq', count: 12, marks: 1 }], full: [{ title: 'English language', type: 'mcq', count: 30, marks: 1 }, { title: 'Reasoning ability', type: 'mcq', count: 35, marks: 1 }, { title: 'Quantitative aptitude', type: 'mcq', count: 35, marks: 1 }] },
  ] },
  { k: 'railways', label: 'Railways (RRB)', presets: [
    { label: 'RRB NTPC — CBT 1', examStyle: 'RRB NTPC CBT 1', real: '100 Q / 100 marks / +1, -0.33 / 90 min', topic: 'RRB NTPC CBT 1 — general awareness, mathematics, general intelligence and reasoning', sections: [{ title: 'General awareness', type: 'mcq', count: 16, marks: 1 }, { title: 'Mathematics', type: 'mcq', count: 12, marks: 1 }, { title: 'General intelligence & reasoning', type: 'mcq', count: 12, marks: 1 }], full: [{ title: 'General awareness', type: 'mcq', count: 40, marks: 1 }, { title: 'Mathematics', type: 'mcq', count: 30, marks: 1 }, { title: 'General intelligence & reasoning', type: 'mcq', count: 30, marks: 1 }] },
    { label: 'RRB Group D', examStyle: 'RRB Group D', real: '100 Q / 100 marks / +1, -0.33 / 90 min', topic: 'RRB Group D — general science, mathematics, general intelligence and reasoning, general awareness', sections: [{ title: 'General science', type: 'mcq', count: 10, marks: 1 }, { title: 'Mathematics', type: 'mcq', count: 10, marks: 1 }, { title: 'General intelligence & reasoning', type: 'mcq', count: 10, marks: 1 }, { title: 'General awareness & current affairs', type: 'mcq', count: 10, marks: 1 }], full: [{ title: 'General science', type: 'mcq', count: 25, marks: 1 }, { title: 'Mathematics', type: 'mcq', count: 25, marks: 1 }, { title: 'General intelligence & reasoning', type: 'mcq', count: 30, marks: 1 }, { title: 'General awareness & current affairs', type: 'mcq', count: 20, marks: 1 }] },
  ] },
  { k: 'teaching', label: 'Teaching (CTET / TET)', presets: [
    { label: 'CTET Paper 1 (Classes 1-5)', examStyle: 'CTET Paper 1', real: '150 Q / 150 marks / +1 / no negative / 2.5 hr', topic: 'CTET Paper 1 — child development and pedagogy, language I and II, mathematics, environmental studies', sections: [{ title: 'Child development & pedagogy', type: 'mcq', count: 10, marks: 1 }, { title: 'Language I', type: 'mcq', count: 8, marks: 1 }, { title: 'Language II', type: 'mcq', count: 8, marks: 1 }, { title: 'Mathematics', type: 'mcq', count: 8, marks: 1 }, { title: 'Environmental studies', type: 'mcq', count: 8, marks: 1 }], full: [{ title: 'Child development & pedagogy', type: 'mcq', count: 30, marks: 1 }, { title: 'Language I', type: 'mcq', count: 30, marks: 1 }, { title: 'Language II', type: 'mcq', count: 30, marks: 1 }, { title: 'Mathematics', type: 'mcq', count: 30, marks: 1 }, { title: 'Environmental studies', type: 'mcq', count: 30, marks: 1 }] },
    { label: 'CTET Paper 2 (Classes 6-8)', examStyle: 'CTET Paper 2', real: '150 Q / 150 marks / +1 / no negative / 2.5 hr', topic: 'CTET Paper 2 — child development and pedagogy, language I and II, mathematics and science', sections: [{ title: 'Child development & pedagogy', type: 'mcq', count: 10, marks: 1 }, { title: 'Language I', type: 'mcq', count: 8, marks: 1 }, { title: 'Language II', type: 'mcq', count: 8, marks: 1 }, { title: 'Mathematics & science', type: 'mcq', count: 14, marks: 1 }], full: [{ title: 'Child development & pedagogy', type: 'mcq', count: 30, marks: 1 }, { title: 'Language I', type: 'mcq', count: 30, marks: 1 }, { title: 'Language II', type: 'mcq', count: 30, marks: 1 }, { title: 'Mathematics & science', type: 'mcq', count: 60, marks: 1 }] },
  ] },
  { k: 'programming', label: 'Programming & IT', presets: [
    { label: 'Java — OOP & collections', examStyle: 'Java', topic: 'Core Java — OOP, collections, exceptions, generics and streams', sections: [{ title: 'Part A — Concepts', type: 'mcq', count: 8, marks: 1 }, { title: 'Part B — Code output', type: 'code', count: 4, marks: 2 }, { title: 'Part C — Short answer', type: 'short', count: 3, marks: 3 }] },
    { label: 'Python basics', examStyle: 'Python', topic: 'Python fundamentals — data types, control flow, functions, lists and dicts', sections: [{ title: 'Part A — Concepts', type: 'mcq', count: 10, marks: 1 }, { title: 'Part B — Output', type: 'code', count: 5, marks: 2 }] },
    { label: 'AWS Solutions Architect', examStyle: 'AWS Certified Solutions Architect Associate', topic: 'AWS SAA — EC2, S3, VPC, IAM, RDS, autoscaling and the well-architected framework', sections: [{ title: 'Domain questions', type: 'mcq', count: 12, marks: 1 }, { title: 'Multi-response', type: 'multi', count: 3, marks: 2 }] },
    { label: 'SQL', examStyle: 'SQL', topic: 'SQL — joins, group by, subqueries, indexing and normalization', sections: [{ title: 'Concepts', type: 'mcq', count: 8, marks: 1 }, { title: 'Query output', type: 'code', count: 4, marks: 2 }] },
  ] },
  { k: 'school', label: 'School (CBSE / State)', presets: [
    { label: 'CBSE Class 10 — Science', examStyle: 'CBSE Class 10', level: 'School', real: '80 marks / 39 Q / matches CBSE board pattern', topic: 'CBSE Class 10 Science — physics, chemistry & biology', sections: [{ title: 'Section A — Multiple choice', type: 'mcq', count: 16, marks: 1 }, { title: 'Section A — Assertion & reason', type: 'assertion', count: 4, marks: 1 }, { title: 'Section B — Short answer', type: 'short', count: 6, marks: 2 }, { title: 'Section C — Short answer', type: 'short', count: 7, marks: 3 }, { title: 'Section D — Long answer', type: 'long', count: 3, marks: 5 }, { title: 'Section E — Case-based', type: 'case', count: 3, marks: 4 }] },
    { label: 'CBSE Class 10 — Mathematics', examStyle: 'CBSE Class 10', level: 'School', real: '80 marks / 38 Q / matches CBSE board pattern', topic: 'CBSE Class 10 Mathematics', sections: [{ title: 'Section A — Multiple choice', type: 'mcq', count: 18, marks: 1 }, { title: 'Section A — Assertion & reason', type: 'assertion', count: 2, marks: 1 }, { title: 'Section B — Short answer', type: 'short', count: 5, marks: 2 }, { title: 'Section C — Short answer', type: 'short', count: 6, marks: 3 }, { title: 'Section D — Long answer', type: 'long', count: 4, marks: 5 }, { title: 'Section E — Case-based', type: 'case', count: 3, marks: 4 }] },
    { label: 'CBSE Class 10 — Social Science', examStyle: 'CBSE Class 10', level: 'School', real: '80 marks / ~37 Q / 5 sections + map work', topic: 'CBSE Class 10 Social Science — history, geography, political science, economics', sections: [{ title: 'Section A — Multiple choice', type: 'mcq', count: 20, marks: 1 }, { title: 'Section B — Very short answer', type: 'short', count: 5, marks: 2 }, { title: 'Section C — Short answer', type: 'short', count: 6, marks: 3 }, { title: 'Section D — Long answer', type: 'long', count: 4, marks: 5 }, { title: 'Section E — Case-based', type: 'case', count: 3, marks: 4 }] },
    { label: 'CBSE Class 12 — Physics', examStyle: 'CBSE Class 12', level: 'School', real: '70 marks / 33 Q / matches CBSE board pattern', topic: 'CBSE Class 12 Physics', sections: [{ title: 'Section A — Multiple choice', type: 'mcq', count: 16, marks: 1 }, { title: 'Section B — Short answer', type: 'short', count: 5, marks: 2 }, { title: 'Section C — Short answer', type: 'short', count: 7, marks: 3 }, { title: 'Section D — Case-based', type: 'case', count: 2, marks: 4 }, { title: 'Section E — Long answer', type: 'long', count: 3, marks: 5 }] },
    { label: 'CBSE Class 12 — Chemistry', examStyle: 'CBSE Class 12', level: 'School', real: '70 marks / 33 Q / matches CBSE board pattern', topic: 'CBSE Class 12 Chemistry', sections: [{ title: 'Section A — Multiple choice', type: 'mcq', count: 16, marks: 1 }, { title: 'Section B — Short answer', type: 'short', count: 5, marks: 2 }, { title: 'Section C — Short answer', type: 'short', count: 7, marks: 3 }, { title: 'Section D — Case-based', type: 'case', count: 2, marks: 4 }, { title: 'Section E — Long answer', type: 'long', count: 3, marks: 5 }] },
    { label: 'CBSE Class 12 — Mathematics', examStyle: 'CBSE Class 12', level: 'School', real: '80 marks / 38 Q / matches CBSE board pattern', topic: 'CBSE Class 12 Mathematics', sections: [{ title: 'Section A — Multiple choice', type: 'mcq', count: 18, marks: 1 }, { title: 'Section A — Assertion & reason', type: 'assertion', count: 2, marks: 1 }, { title: 'Section B — Short answer', type: 'short', count: 5, marks: 2 }, { title: 'Section C — Short answer', type: 'short', count: 6, marks: 3 }, { title: 'Section D — Long answer', type: 'long', count: 4, marks: 5 }, { title: 'Section E — Case-based', type: 'case', count: 3, marks: 4 }] },
    { label: 'CBSE Class 12 — Biology', examStyle: 'CBSE Class 12', level: 'School', real: '70 marks / 33 Q / matches CBSE board pattern', topic: 'CBSE Class 12 Biology', sections: [{ title: 'Section A — Multiple choice', type: 'mcq', count: 16, marks: 1 }, { title: 'Section B — Short answer', type: 'short', count: 5, marks: 2 }, { title: 'Section C — Short answer', type: 'short', count: 7, marks: 3 }, { title: 'Section D — Case-based', type: 'case', count: 2, marks: 4 }, { title: 'Section E — Long answer', type: 'long', count: 3, marks: 5 }] },
  ] },
  { k: 'medical', label: 'Medical & nursing', presets: [
    { label: 'NEET — Biology', examStyle: 'NEET', real: 'NEET Biology = 90 Q (Botany 45 + Zoology 45); full NEET 180 Q / 720 / +4, -1', topic: 'NEET Biology — botany & zoology', sections: [{ title: 'Botany', type: 'mcq', count: 25, marks: 4 }, { title: 'Zoology', type: 'mcq', count: 25, marks: 4 }], full: [{ title: 'Botany', type: 'mcq', count: 45, marks: 4 }, { title: 'Zoology', type: 'mcq', count: 45, marks: 4 }] },
    { label: 'NEET — Full (Physics, Chemistry, Biology)', examStyle: 'NEET', real: '180 Q / 720 marks / +4, -1 (Phy 45, Chem 45, Bio 90)', topic: 'NEET UG — physics, chemistry, botany and zoology', sections: [{ title: 'Physics', type: 'mcq', count: 10, marks: 4 }, { title: 'Chemistry', type: 'mcq', count: 10, marks: 4 }, { title: 'Botany', type: 'mcq', count: 10, marks: 4 }, { title: 'Zoology', type: 'mcq', count: 10, marks: 4 }], full: [{ title: 'Physics', type: 'mcq', count: 45, marks: 4 }, { title: 'Chemistry', type: 'mcq', count: 45, marks: 4 }, { title: 'Botany', type: 'mcq', count: 45, marks: 4 }, { title: 'Zoology', type: 'mcq', count: 45, marks: 4 }] },
  ] },
  { k: 'engineering', label: 'Engineering / entrance', presets: [
    { label: 'JEE Main', examStyle: 'JEE Main', real: '75 Q / 300 marks / +4, -1 / per subject 20 MCQ + 5 numeric', topic: 'JEE Main — physics, chemistry & mathematics', sections: [{ title: 'Physics — MCQ', type: 'mcq', count: 8, marks: 4 }, { title: 'Physics — Numeric', type: 'numeric', count: 4, marks: 4 }, { title: 'Chemistry — MCQ', type: 'mcq', count: 8, marks: 4 }, { title: 'Chemistry — Numeric', type: 'numeric', count: 4, marks: 4 }, { title: 'Mathematics — MCQ', type: 'mcq', count: 8, marks: 4 }, { title: 'Mathematics — Numeric', type: 'numeric', count: 4, marks: 4 }], full: [{ title: 'Physics — MCQ', type: 'mcq', count: 20, marks: 4 }, { title: 'Physics — Numeric', type: 'numeric', count: 5, marks: 4 }, { title: 'Chemistry — MCQ', type: 'mcq', count: 20, marks: 4 }, { title: 'Chemistry — Numeric', type: 'numeric', count: 5, marks: 4 }, { title: 'Mathematics — MCQ', type: 'mcq', count: 20, marks: 4 }, { title: 'Mathematics — Numeric', type: 'numeric', count: 5, marks: 4 }] },
    { label: 'GATE — CS & IT', examStyle: 'GATE Computer Science', real: '65 Q / 100 marks / MCQ + MSQ + NAT / 1/3 negative on MCQ only', topic: 'GATE Computer Science — algorithms, data structures, OS, DBMS, networks, TOC, digital logic and engineering mathematics', sections: [{ title: 'General aptitude', type: 'mcq', count: 10, marks: 1 }, { title: 'Core — multiple choice', type: 'mcq', count: 20, marks: 2 }, { title: 'Core — numerical answer', type: 'numeric', count: 10, marks: 2 }], full: [{ title: 'General aptitude', type: 'mcq', count: 10, marks: 1 }, { title: 'Core — multiple choice', type: 'mcq', count: 30, marks: 2 }, { title: 'Core — numerical answer', type: 'numeric', count: 25, marks: 2 }] },
  ] },
  { k: 'law', label: 'Law (CLAT)', presets: [
    { label: 'CLAT UG', examStyle: 'CLAT UG', real: '120 Q / 120 marks / +1, -0.25 / 2 hr', topic: 'CLAT UG — English, current affairs & GK, legal reasoning, logical reasoning, quantitative techniques', sections: [{ title: 'English language', type: 'mcq', count: 8, marks: 1 }, { title: 'Current affairs & GK', type: 'mcq', count: 10, marks: 1 }, { title: 'Legal reasoning', type: 'mcq', count: 10, marks: 1 }, { title: 'Logical reasoning', type: 'mcq', count: 8, marks: 1 }, { title: 'Quantitative techniques', type: 'mcq', count: 4, marks: 1 }], full: [{ title: 'English language', type: 'mcq', count: 24, marks: 1 }, { title: 'Current affairs & GK', type: 'mcq', count: 28, marks: 1 }, { title: 'Legal reasoning', type: 'mcq', count: 30, marks: 1 }, { title: 'Logical reasoning', type: 'mcq', count: 24, marks: 1 }, { title: 'Quantitative techniques', type: 'mcq', count: 14, marks: 1 }] },
  ] },
  { k: 'university', label: 'University entrance (CUET)', presets: [
    { label: 'CUET UG \u2014 General Test', examStyle: 'CUET UG General Test', real: '60 Q (attempt 50) / 250 marks / +5, -1 / ~1 hr', topic: 'CUET UG General Test \u2014 general knowledge, current affairs, general mental ability, numerical ability, and logical & analytical reasoning', sections: [{ title: 'GK & current affairs', type: 'mcq', count: 8, marks: 5 }, { title: 'Numerical ability', type: 'mcq', count: 8, marks: 5 }, { title: 'Logical & analytical reasoning', type: 'mcq', count: 8, marks: 5 }], full: [{ title: 'GK & current affairs', type: 'mcq', count: 20, marks: 5 }, { title: 'Numerical ability', type: 'mcq', count: 20, marks: 5 }, { title: 'Logical & analytical reasoning', type: 'mcq', count: 20, marks: 5 }] },
  ] },
  { k: 'languages', label: 'Languages', presets: [
    { label: 'English grammar', examStyle: 'English', topic: 'English grammar — tenses, prepositions, articles and sentence correction', sections: [{ title: 'Grammar MCQ', type: 'mcq', count: 10, marks: 1 }, { title: 'Fill the blanks', type: 'fill', count: 5, marks: 1 }] },
  ] },
  { k: 'custom', label: 'Custom', presets: [] },
];
